### ISSUE TITLE
Builds should be done in isolated containers

### ISSUE THREAD

**Issue by birkholz** [ZeroCater/linty#57]

**Comment by jadengore** [comment]
Do you no longer have plans for isolated containers?

**Comment by birkholz** [comment]
The idea was first brought up when we were doing JS linting via `npm` commands. However, with #112 , we removed the use of npm in favor of server-installed eslint. Originally, isolated containers were considered to prevent any malicious activity from npm scripts. However, the possibilities for abuse were too numerous, so we decided to use server-installed binaries for linters instead, thus removing the need for isolation.

**Comment by jadengore** [comment]
So people have to request adding ESLint configurations?

**Comment by birkholz** [comment]
If you have an `.eslintrc` file in your repo, it should be respected. And I have most of the common plugins available for extending. But any plugins that are not available will have to be requested. This is standard practice by most other linting services.
