### ISSUE TITLE
Users should be able to re-run a build

### ISSUE THREAD

**Issue by birkholz** [ZeroCater/linty#58]
Re-running a build will lint the same SHA as before, and overwrite the previous results.

**Comment by jadengore** [comment]
@birkholz What exactly does this mean?

**Comment by birkholz** [comment]
Circle CI has a "rebuild" button. It means it takes the same SHA, and reruns the tests. I want a similar button for linty, in case of weird issues from a deploy or something.

**Comment by jadengore** [comment]
@birkholz _Erasing previous builds_ makes this task a bit unclear.

**Comment by birkholz** [comment]
@jadengore I rewrote the title and desc.

**Comment by jadengore** [comment]
👏
