### ISSUE TITLE
Support a setup.cfg file

### ISSUE THREAD

**Issue by kavdev** [ZeroCater/linty#72]
Hi! First off, great service! It took a while to find this, but it's exactly what I needed for my pipeline.

I have a `setup.cfg` file in the root of my directory for using flake8 locally. Having that file seems to set the linty pydocstyle config to its defaults. I added a `[pydocstyle]` directive in the setup.cfg (supported) file to see if that would work, but no dice.

**Comment by birkholz** [comment]
@kavdev Hi there! First off, it's awesome to know someone actually discovered Linty.
Second, I apologize for the late response. Work on Linty has been paused for a while, but work is resuming very soon. 

Thanks for the issue report. I've encountered a similar issue myself, and I suspect its just because of an old version of `pycodestyle`. When I renamed the directive from `[pycodestyle]` to `[pep8]`, it worked. I'm not sure about `pydocstyle` though, I'm not familiar with it. I'll look into it.

**Comment by kavdev** [comment]
@birkholz: It took me a long time to find it, but I'm very glad I did. I'm working on adding it to the CI pipeline for a bunch of my projects. Keep me posted on what you find for this issue.

**Comment by birkholz** [comment]
@kavdev I'll definitely update this issue when it is resolved.

**Comment by birkholz** [comment]
@kavdev I've updated the version of `pycodestyle` used in #77 , and its deployed. I'm testing the `[pydocstyle]` directive now.

**Comment by birkholz** [comment]
@kavdev Alright, so `[pydocstyle]` is only used when running [pydocstyle](https://github.com/PyCQA/pydocstyle). At the moment, Linty runs `pycodestyle` to lint Python code. I'll be changing this soon to run `flake8` instead.

I'm going to close this ticket as "wontfix". If you wish to request support for `pydocstyle`, you may open a new ticket.

**Comment by kavdev** [comment]
@birkholz: Wow. I totally got myself confused with pydocstyle and pycodestyle. There was a conversation going on over at [dj-stripe](https://github.com/kavdev/dj-stripe/issues/339) that concerned pydocstyle. Either way, I see the ``setup.cfg`` file was causing issues, hence #77. I have the ``setup.cfg`` set for local development with a ``flake8`` directive, so I'm glad you'll be switching over soon.

I'll un-gitignore the setup.cfg files and see how things go. I'll keep you posted.

**Comment by kavdev** [comment]
@birkholz: Alright, so it works as expected now.

Note that if you include a ``setup.cfg`` file and it doesn't include a ``[pycodestyle]`` directive, Linty's defaults get cleared. For instance, we had ``[flake8]`` and ``[pydocstyle]`` in our ``setup.cfg`` file but no ``[pycodestyle]``.

What do you think about this flow:
- check if the repo has a ``setup.cfg`` file
- if it does
    - check if a ``[pycodestyle]`` directive exists
    - if it does
        - use the file
    - if it does not
        - inject Linty's ``[pycodestyle]`` defaults into the setup file
- if it does not
    - create a ``setup.cfg`` file
    - inject Linty's ``[pycodestyle]`` defaults into the setup file

(then run the linter)

**Comment by birkholz** [comment]
At the moment, Linty is just running pycodestyle, which does its own decision making in that regard. So Linty doesn't have any defaults of its own, it's essentially just "All rules" from pycodestyle.

**Comment by kavdev** [comment]
@birkholz: So where are the 119 max line length and ignoring the migrations folder settings coming from?

**Comment by birkholz** [comment]
@kavdev Is it really using those settings for your projects? I wasn't aware. My understanding was that pycodestyle uses the `setup.cfg` in the root of the directory its called in. I'll look into it.

**Comment by kavdev** [comment]
@birkholz:

* If I don't include a ``setup.cfg`` in the repo, it uses those.
* If I include a ``setup.cfg`` in the repo but it does not include a ``[pycodestyle]`` directive, the defaults according to PEP8 are used (pycodestyle defaults)
* If I include a ``setup.cfg`` in the repo with a ``[pycodestyle]`` directive and associated preferences, those preferences are used

**Comment by birkholz** [comment]
@kavdev Yea, that's definitely unintended.

Linty should:
1. Use pycodestyle defaults if no config is present
2. Use pycodestyle defaults overridden by config

in that order. The `setup.cfg` file in this repo shouldn't be affecting the results.

**Comment by kavdev** [comment]
@birkholz: That makes more sense haha

**Comment by birkholz** [comment]
@kavdev Pycodestyle recently made a new release, so I've locked Linty on 2.2.0. Please let me know if you're still seeing issues with the rules.

**Comment by kavdev** [comment]
@birkholz: Looks like it's working

**Comment by birkholz** [comment]
Resolved by excluding linty's own `setup.cfg` in #110
