### ISSUE TITLE
E305 False Negative

### ISSUE THREAD

**Issue by birkholz** [ZeroCater/linty#91]
There's an [upstream bug](https://github.com/PyCQA/pycodestyle/pull/555#issuecomment-235330443) in pycodestyle causing false negatives for E305. When the issue is fixed there, I'll deploy it to Linty.

@kavdev I noticed you had a failed build. This is the cause.

**Comment by kavdev** [comment]
@birkholz: how much of a pain would it be to switch to flake8?

**Comment by birkholz** [comment]
@kavdev Not very. I already attempted switching with #78, and reverted with #79. It's more of an issue with the current status of pycodestyle.

The problem is that there hasn't been a release of pycodestyle since May 31st (2.0.0), but there have been some really important changes since then. One particular change is how `setup.cfg` is read (https://github.com/PyCQA/pycodestyle/pull/530). Flake8 installs the latest release of pycodestyle, which means its stuck on 2.0.0 until a new release.

So I had two options until a new release was created:
1. Use master of the repo
2. Cherry-pick changes and have Linty use a fork

Option 1 was clearly the easier one, and it's only temporary. The E305 issue should be patched upstream before the next release, at which point Linty will update to use the patched version. The author who introduced the bug said [he was going to fix it soon](https://github.com/PyCQA/pycodestyle/pull/555#issuecomment-239157557). And as soon as a new release is available, I'll migrate Linty to use flake8 (again).

Unfortunately, in the meantime, the best course of action is to add E305 to your ignore list in `setup.cfg`, otherwise you'll most likely get false failures.

**Comment by kavdev** [comment]
@birkholz: Sounds good. I'll keep an eye out.

**Comment by birkholz** [comment]
@kavdev I'm adding E305 as a forced ignore for now. When its fixed upstream, I'll remove the ignore.
